name: Send Discord Message

on:
  repository_dispatch:
    types: [send-discord]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"${{ github.event.client_payload.message }}\"}" \
               "$DISCORD_WEBHOOK"
